### ISSUE TITLE
Location search not working

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/Mapping#38] opened 2017-10-24 18:10 UTC
The search by name option to assign a point is only spinning, not returning results. Currently on latest commit of branch master.

**Comment by mebrett** [comment] 2017-10-24 18:11
<img width="425" alt="screen shot 2017-10-24 at 2 10 00 pm" src="https://user-images.githubusercontent.com/2314070/31960244-2866efc4-b8c5-11e7-8614-a4a907ff62a5.png">

**Comment by jimsafley** [comment] 2017-10-25 20:30
I can't reproduce this. Do you see any errors in your browser's console after entering a search?

**Comment by Daniel-KM** [comment] 2018-04-09 04:45
I had the same issue in one browser but not another one, and it is fixed in #41.

**Closed as completed** 2018-04-09 15:37 UTC
